// Generated by Haxe 4.0.0-preview.5
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Sys extends haxe.lang.HxObject
{
	public Sys(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Sys()
	{
		//line 27 "/usr/local/share/haxe/std/java/_std/Sys.hx"
		haxe.root.Sys.__hx_ctor__Sys(this);
	}
	
	
	protected static void __hx_ctor__Sys(haxe.root.Sys __hx_this)
	{
	}
	
	
	public static java.lang.String[] _args;
	
	public static haxe.root.Array<java.lang.String> args()
	{
		//line 44 "/usr/local/share/haxe/std/java/_std/Sys.hx"
		if (( haxe.root.Sys._args == null )) 
		{
			//line 45 "/usr/local/share/haxe/std/java/_std/Sys.hx"
			return new haxe.root.Array<java.lang.String>(new java.lang.String[]{});
		}
		
		//line 46 "/usr/local/share/haxe/std/java/_std/Sys.hx"
		return haxe.java.Lib.array_String(haxe.root.Sys._args);
	}
	
	
}


