// Generated by Haxe 4.0.0-preview.5
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	var bench = new Bencher();
	bench.intArithmetic(50000000);
	print("Main.hx:6:","Hello World");
};
var Bencher = function() {
};
Bencher.prototype = {
	intArithmetic: function(intMax) {
		var intResult = 1;
		var myIterator_min = 0;
		var myIterator_max = intMax;
		while(myIterator_min < myIterator_max) {
			var i = myIterator_min++;
			intResult -= i;
			++i;
			intResult += i;
			++i;
			intResult *= i;
			++i;
			intResult = intResult / i | 0;
			++i;
		}
	}
};
Main.main();
})();
