<?php
/**
 * Generated by Haxe 4.0.0-preview.5
 */

namespace php\_Boot;

use \php\Boot;

/**
 * Closures implementation
 */
class HxClosure {
	/**
	 * @var mixed
	 * A callable value, which can be invoked by PHP
	 */
	public $callable;
	/**
	 * @var string
	 * Method name for methods
	 */
	public $func;
	/**
	 * @var mixed
	 * `this` for instance methods; php class name for static methods
	 */
	public $target;

	/**
	 * @param mixed $target
	 * @param string $func
	 * 
	 * @return void
	 */
	public function __construct ($target, $func) {
		#/usr/local/share/haxe/std/php/Boot.hx:898: characters 3-23
		$this->target = $target;
		#/usr/local/share/haxe/std/php/Boot.hx:899: characters 3-19
		$this->func = $func;
		#/usr/local/share/haxe/std/php/Boot.hx:901: lines 901-903
		if (is_null($target)) {
			#/usr/local/share/haxe/std/php/Boot.hx:902: characters 4-9
			throw new HxException("Unable to create closure on `null`");
		}
		#/usr/local/share/haxe/std/php/Boot.hx:904: characters 14-98
		$tmp = null;
		if (($target instanceof HxAnon)) {
			#/usr/local/share/haxe/std/php/Boot.hx:904: characters 52-58
			$tmp1 = $target;
			#/usr/local/share/haxe/std/php/Boot.hx:904: characters 14-98
			$tmp = $tmp1->{$func};
		} else {
			$tmp = [$target, $func];
		}
		#/usr/local/share/haxe/std/php/Boot.hx:904: characters 3-98
		$this->callable = $tmp;
	}

	/**
	 * @see http://php.net/manual/en/language.oop5.magic.php#object.invoke
	 * 
	 * @return mixed
	 */
	public function __invoke () {
		#/usr/local/share/haxe/std/php/Boot.hx:912: characters 3-71
		return call_user_func_array($this->callable, func_get_args());
	}

	/**
	 * Invoke this closure with `newThis` instead of `this`
	 * 
	 * @param mixed $newThis
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	public function callWith ($newThis, $args) {
		#/usr/local/share/haxe/std/php/Boot.hx:939: characters 3-65
		return call_user_func_array($this->getCallback($newThis), $args);
	}

	/**
	 * Check if this is the same closure
	 * 
	 * @param HxClosure $closure
	 * 
	 * @return bool
	 */
	public function equals ($closure) {
		#/usr/local/share/haxe/std/php/Boot.hx:932: characters 10-60
		if (Boot::equal($this->target, $closure->target)) {
			#/usr/local/share/haxe/std/php/Boot.hx:932: characters 39-59
			return $this->func === $closure->func;
		} else {
			#/usr/local/share/haxe/std/php/Boot.hx:932: characters 10-60
			return false;
		}
	}

	/**
	 * Generates callable value for PHP
	 * 
	 * @param mixed $eThis
	 * 
	 * @return mixed
	 */
	public function getCallback ($eThis = null) {
		#/usr/local/share/haxe/std/php/Boot.hx:919: lines 919-921
		if ($eThis === null) {
			#/usr/local/share/haxe/std/php/Boot.hx:920: characters 4-18
			$eThis = $this->target;
		}
		#/usr/local/share/haxe/std/php/Boot.hx:922: lines 922-924
		if (($eThis instanceof HxAnon)) {
			#/usr/local/share/haxe/std/php/Boot.hx:923: characters 24-29
			$tmp = $eThis;
			#/usr/local/share/haxe/std/php/Boot.hx:923: characters 4-36
			return $tmp->{$this->func};
		}
		#/usr/local/share/haxe/std/php/Boot.hx:925: characters 3-39
		return [$eThis, $this->func];
	}
}

Boot::registerClass(HxClosure::class, 'php._Boot.HxClosure');
