<?php
/**
 * Generated by Haxe 4.0.0-preview.5
 */

namespace php\_Boot;

use \php\Boot;

/**
 * Class<T> implementation for Haxe->PHP internals.
 */
class HxClass {
	/**
	 * @var string
	 */
	public $phpClassName;

	/**
	 * @param string $phpClassName
	 * 
	 * @return void
	 */
	public function __construct ($phpClassName) {
		#/usr/local/share/haxe/std/php/Boot.hx:599: characters 3-35
		$this->phpClassName = $phpClassName;
	}

	/**
	 * Magic method to call static methods of this class, when `HxClass` instance is in a `Dynamic` variable.
	 * 
	 * @param string $method
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	public function __call ($method, $args) {
		#/usr/local/share/haxe/std/php/Boot.hx:607: characters 3-111
		$callback = ((($this->phpClassName === "String" ? HxString::class : $this->phpClassName))??'null') . "::" . ($method??'null');
		#/usr/local/share/haxe/std/php/Boot.hx:608: characters 3-53
		return call_user_func_array($callback, $args);
	}

	/**
	 * Magic method to get static vars of this class, when `HxClass` instance is in a `Dynamic` variable.
	 * 
	 * @param string $property
	 * 
	 * @return mixed
	 */
	public function __get ($property) {
		#/usr/local/share/haxe/std/php/Boot.hx:616: lines 616-624
		if (defined("" . ($this->phpClassName??'null') . "::" . ($property??'null'))) {
			#/usr/local/share/haxe/std/php/Boot.hx:617: characters 4-54
			return constant("" . ($this->phpClassName??'null') . "::" . ($property??'null'));
		} else if (Boot::hasGetter($this->phpClassName, $property)) {
			#/usr/local/share/haxe/std/php/Boot.hx:619: characters 29-41
			$tmp = $this->phpClassName;
			#/usr/local/share/haxe/std/php/Boot.hx:619: characters 4-59
			return $tmp::{"get_" . ($property??'null')}();
		} else if (method_exists($this->phpClassName, $property)) {
			#/usr/local/share/haxe/std/php/Boot.hx:621: characters 4-48
			return new HxClosure($this->phpClassName, $property);
		} else {
			#/usr/local/share/haxe/std/php/Boot.hx:623: characters 33-45
			$tmp1 = $this->phpClassName;
			#/usr/local/share/haxe/std/php/Boot.hx:623: characters 4-56
			return $tmp1::${$property};
		}
	}

	/**
	 * Magic method to set static vars of this class, when `HxClass` instance is in a `Dynamic` variable.
	 * 
	 * @param string $property
	 * @param mixed $value
	 * 
	 * @return void
	 */
	public function __set ($property, $value) {
		#/usr/local/share/haxe/std/php/Boot.hx:632: lines 632-636
		if (Boot::hasSetter($this->phpClassName, $property)) {
			#/usr/local/share/haxe/std/php/Boot.hx:633: characters 22-34
			$tmp = $this->phpClassName;
			#/usr/local/share/haxe/std/php/Boot.hx:633: characters 4-59
			$tmp::{"set_" . ($property??'null')}($value);
		} else {
			#/usr/local/share/haxe/std/php/Boot.hx:635: characters 26-38
			$tmp1 = $this->phpClassName;
			#/usr/local/share/haxe/std/php/Boot.hx:635: characters 4-56
			$tmp1::${$property} = $value;
		}
	}
}

Boot::registerClass(HxClass::class, 'php._Boot.HxClass');
