<?php
/**
 * Generated by Haxe 4.0.0-preview.5
 */

namespace php\_Boot;

use \php\Boot;

/**
 * For Dynamic access which looks like String.
 * Instances of this class should not be saved anywhere.
 * Instead it should be used to immediately invoke a String field right after instance creation one time only.
 */
class HxDynamicStr extends HxClosure {
	/**
	 * @var string
	 */
	static public $hxString;

	/**
	 * @param string $str
	 * @param string $method
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	static public function invoke ($str, $method, $args) {
		#/usr/local/share/haxe/std/php/Boot.hx:803: characters 3-34
		array_unshift($args, $str);
		#/usr/local/share/haxe/std/php/Boot.hx:804: characters 3-69
		return call_user_func_array((HxDynamicStr::$hxString??'null') . "::" . ($method??'null'), $args);
	}

	/**
	 * Returns HxDynamicStr instance if `value` is a string.
	 * Otherwise returns `value` as-is.
	 * 
	 * @param mixed $value
	 * 
	 * @return mixed
	 */
	static public function wrap ($value) {
		#/usr/local/share/haxe/std/php/Boot.hx:795: lines 795-799
		if (is_string($value)) {
			#/usr/local/share/haxe/std/php/Boot.hx:796: characters 4-34
			return new HxDynamicStr($value);
		} else {
			#/usr/local/share/haxe/std/php/Boot.hx:798: characters 4-16
			return $value;
		}
	}

	/**
	 * @param string $str
	 * 
	 * @return void
	 */
	public function __construct ($str) {
		#/usr/local/share/haxe/std/php/Boot.hx:808: characters 3-19
		parent::__construct($str, null);
	}

	/**
	 * @param string $method
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	public function __call ($method, $args) {
		#/usr/local/share/haxe/std/php/Boot.hx:824: characters 10-38
		array_unshift($args, $this->target);
		return call_user_func_array((HxDynamicStr::$hxString??'null') . "::" . ($method??'null'), $args);
	}

	/**
	 * @param string $field
	 * 
	 * @return mixed
	 */
	public function __get ($field) {
		#/usr/local/share/haxe/std/php/Boot.hx:813: lines 813-819
		if ($field === "length") {
			#/usr/local/share/haxe/std/php/Boot.hx:815: characters 5-34
			return mb_strlen($this->target);
		} else {
			#/usr/local/share/haxe/std/php/Boot.hx:817: characters 5-17
			$this->func = $field;
			#/usr/local/share/haxe/std/php/Boot.hx:818: characters 5-16
			return $this;
		}
	}

	/**
	 * @see http://php.net/manual/en/language.oop5.magic.php#object.invoke
	 * 
	 * @return mixed
	 */
	public function __invoke () {
		#/usr/local/share/haxe/std/php/Boot.hx:832: characters 10-54
		$str = $this->target;
		$method = $this->func;
		$args = func_get_args();
		array_unshift($args, $str);
		return call_user_func_array((HxDynamicStr::$hxString??'null') . "::" . ($method??'null'), $args);
	}

	/**
	 * Invoke this closure with `newThis` instead of `this`
	 * 
	 * @param mixed $newThis
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	public function callWith ($newThis, $args) {
		#/usr/local/share/haxe/std/php/Boot.hx:849: lines 849-851
		if ($newThis === null) {
			#/usr/local/share/haxe/std/php/Boot.hx:850: characters 4-20
			$newThis = $this->target;
		}
		#/usr/local/share/haxe/std/php/Boot.hx:852: characters 10-37
		$method = $this->func;
		array_unshift($args, $newThis);
		return call_user_func_array((HxDynamicStr::$hxString??'null') . "::" . ($method??'null'), $args);
	}

	/**
	 * Generates callable value for PHP
	 * 
	 * @param mixed $eThis
	 * 
	 * @return mixed
	 */
	public function getCallback ($eThis = null) {
		#/usr/local/share/haxe/std/php/Boot.hx:839: lines 839-841
		if ($eThis === null) {
			#/usr/local/share/haxe/std/php/Boot.hx:840: characters 4-49
			return [$this, $this->func];
		}
		#/usr/local/share/haxe/std/php/Boot.hx:842: characters 3-67
		return [new HxDynamicStr($eThis), $this->func];
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$hxString = Boot::getClass(HxString::class)->phpClassName;
	}
}

Boot::registerClass(HxDynamicStr::class, 'php._Boot.HxDynamicStr');
HxDynamicStr::__hx__init();
