<?php
/**
 * Generated by Haxe 4.0.0-preview.5
 */

namespace php\_Boot;

use \php\Boot;

/**
 * Special exception which is used to wrap non-throwable values
 */
class HxException extends \Exception {
	/**
	 * @var mixed
	 */
	public $e;

	/**
	 * @param mixed $e
	 * 
	 * @return void
	 */
	public function __construct ($e) {
		#/usr/local/share/haxe/std/php/Boot.hx:951: characters 4-14
		$this->e = $e;
		#/usr/local/share/haxe/std/php/Boot.hx:952: characters 4-28
		parent::__construct(Boot::stringify($e));
	}
}

Boot::registerClass(HxException::class, 'php._Boot.HxException');
