// Generated by Haxe 4.0.0-preview.5
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Enum
{
	public Enum(int index)
	{
		//line 232 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		this.index = index;
	}
	
	
	public final int index;
	
	public java.lang.String getTag()
	{
		//line 237 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		throw haxe.lang.HaxeException.wrap("Not Implemented");
	}
	
	
	public haxe.root.Array<java.lang.Object> getParams()
	{
		//line 242 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		return new haxe.root.Array<java.lang.Object>(new java.lang.Object[]{});
	}
	
	
	@Override public java.lang.String toString()
	{
		//line 247 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		return this.getTag();
	}
	
	
}


