// Generated by Haxe 4.0.0-preview.5
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/usr/local/share/haxe/std/cpp/_std/Std.hx",
"/usr/local/share/haxe/std/cpp/_std/haxe/Log.hx",
"?",
"Main.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/usr/local/share/haxe/std/cpp/_std/Std.hx",
"/usr/local/share/haxe/std/cpp/_std/haxe/Log.hx",
"?",
"/data/Main.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Main",
"Bencher",
"Std",
"haxe.Log",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(hx::__hxcpp_all_classes, hx::__hxcpp_all_files_fullpath); }
