// Generated by Haxe 4.0.0-preview.5
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ParamEnum extends haxe.lang.Enum
{
	public ParamEnum(int index, java.lang.Object[] params)
	{
		//line 258 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		super(index);
		//line 259 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		this.params = params;
	}
	
	
	public final java.lang.Object[] params;
	
	@Override public haxe.root.Array<java.lang.Object> getParams()
	{
		//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		if (( this.params == null )) 
		{
			//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			return new haxe.root.Array<java.lang.Object>(new java.lang.Object[]{});
		}
		else
		{
			//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			java.lang.Object[] this1 = this.params;
			//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			haxe.root.Array a = new haxe.root.Array();
			//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			int len = ((java.lang.Object[]) (this1) ).length;
			//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			{
				//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				int _g = 0;
				//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				int _g1 = len;
				//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				while (( _g < _g1 ))
				{
					//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
					int i = _g++;
					//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
					a.__set(i, ((java.lang.Object) (((java.lang.Object[]) (this1) )[i]) ));
				}
				
			}
			
			//line 264 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			return ((haxe.root.Array<java.lang.Object>) (a) );
		}
		
	}
	
	
	@Override public java.lang.String toString()
	{
		//line 269 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		if (( ( this.params == null ) || ( ((java.lang.Object[]) (this.params) ).length == 0 ) )) 
		{
			//line 269 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			return this.getTag();
		}
		
		//line 270 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		haxe.root.StringBuf ret = new haxe.root.StringBuf();
		//line 271 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		ret.add(haxe.lang.Runtime.toString(this.getTag()));
		//line 271 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		ret.add(haxe.lang.Runtime.toString("("));
		//line 272 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		boolean first = true;
		//line 273 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		{
			//line 273 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			int _g = 0;
			//line 273 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			java.lang.Object[] _g1 = this.params;
			//line 273 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			while (( _g < ((java.lang.Object[]) (_g1) ).length ))
			{
				//line 273 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				java.lang.Object p = ((java.lang.Object) (((java.lang.Object[]) (_g1) )[_g]) );
				//line 273 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				 ++ _g;
				//line 275 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				if (first) 
				{
					//line 276 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
					first = false;
				}
				else
				{
					//line 278 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
					ret.add(haxe.lang.Runtime.toString(","));
				}
				
				//line 279 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				ret.add(((java.lang.Object) (p) ));
			}
			
		}
		
		//line 281 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		ret.add(haxe.lang.Runtime.toString(")"));
		//line 282 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		return ret.toString();
	}
	
	
	@Override public boolean equals(java.lang.Object obj)
	{
		//line 287 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		if (haxe.lang.Runtime.eq(obj, this)) 
		{
			//line 288 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			return true;
		}
		
		//line 289 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		haxe.lang.ParamEnum obj1 = ( (( obj instanceof haxe.lang.ParamEnum )) ? (((haxe.lang.ParamEnum) (obj) )) : (null) );
		//line 290 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		boolean ret = ( ( ( obj1 != null ) && haxe.root.Std.is(obj1, haxe.root.Type.getEnum(((java.lang.Object) (this) ))) ) && ( obj1.index == this.index ) );
		//line 291 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		if ( ! (ret) ) 
		{
			//line 292 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			return false;
		}
		
		//line 293 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		if (( obj1.params == this.params )) 
		{
			//line 294 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			return true;
		}
		
		//line 295 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		int len = 0;
		//line 296 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		boolean tmp = false;
		//line 296 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		if ( ! ((( ( obj1.params == null ) || ( this.params == null ) ))) ) 
		{
			//line 296 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			len = ((java.lang.Object[]) (this.params) ).length;
			//line 296 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			tmp = ( len != ((java.lang.Object[]) (obj1.params) ).length );
		}
		else
		{
			//line 296 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			tmp = true;
		}
		
		//line 296 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		if (tmp) 
		{
			//line 297 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			return false;
		}
		
		//line 298 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		{
			//line 298 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			int _g = 0;
			//line 298 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			int _g1 = len;
			//line 298 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			while (( _g < _g1 ))
			{
				//line 298 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				int i = _g++;
				//line 300 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				if ( ! (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.root.Type.enumEq(((java.lang.Object) (((java.lang.Object[]) (obj1.params) )[i]) ), ((java.lang.Object) (((java.lang.Object[]) (this.params) )[i]) ))) ))) ) 
				{
					//line 301 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
					return false;
				}
				
			}
			
		}
		
		//line 303 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		return true;
	}
	
	
	@Override public int hashCode()
	{
		//line 308 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		int h = 19;
		//line 309 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		if (( this.params != null )) 
		{
			//line 309 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			int _g = 0;
			//line 309 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			java.lang.Object[] _g1 = this.params;
			//line 309 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
			while (( _g < ((java.lang.Object[]) (_g1) ).length ))
			{
				//line 309 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				java.lang.Object p = ((java.lang.Object) (((java.lang.Object[]) (_g1) )[_g]) );
				//line 309 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				 ++ _g;
				//line 311 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				h *= 31;
				//line 312 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
				if (( ! (( p == null )) )) 
				{
					//line 313 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
					h = ((int) (haxe.lang.Runtime.toInt(((java.lang.Object) (haxe.lang.Runtime.plus(h, p.hashCode())) ))) );
				}
				
			}
			
		}
		
		//line 315 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		h += this.index;
		//line 316 "/usr/local/share/haxe/std/java/internal/HxObject.hx"
		return h;
	}
	
	
}


