<?php
/**
 * Generated by Haxe 4.0.0-preview.5
 */

use \php\Boot;

/**
 * This class gives you access to many base functionalities of system platforms. Looks in `sys` sub packages for more system APIs.
 */
class Sys {
	/**
	 * Returns all the arguments that were passed by the command line.
	 * 
	 * @return \Array_hx
	 */
	static public function args () {
		#/usr/local/share/haxe/std/php/_std/Sys.hx:40: lines 40-44
		if (array_key_exists("argv", $_SERVER)) {
			#/usr/local/share/haxe/std/php/_std/Sys.hx:41: characters 4-89
			return \Array_hx::wrap(array_slice($_SERVER["argv"], 1));
		} else {
			#/usr/local/share/haxe/std/php/_std/Sys.hx:43: characters 4-13
			return new \Array_hx();
		}
	}
}

Boot::registerClass(Sys::class, 'Sys');
